language: dart
dart:
  - dev
cache:
  directories:
    - $HOME/.npm
    - $HOME/.nvm
    - $HOME/.pub-cache/hosted
    - $HOME/.chrome/canary
    - node_modules
before_install:
  - pub global activate dart_coveralls
  - export CHROME_CANARY_BIN=`./tool/get_chrome_canary.sh`
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - nvm install 5.5.0
  - npm install
script:
  #- ./tool/presubmit.sh && ./tool/coverage.sh
  - ./tool/$TEST.sh
env:
  - TEST=check_expectations_were_built
  - TEST=coverage
  - TEST=test
  - TEST=browser_test
  - TEST=node_test
  - TEST=analyze
  - TEST=format
  - TEST=transformer_test
