language: dart
dart:
  - dev
cache:
  directories:
    - $HOME/.npm
    - $HOME/.nvm
    - $HOME/.pub-cache/hosted
    - $HOME/.chrome/canary
    - node_modules
before_install:
  - pub global activate dart_coveralls
  - export CHROME_CANARY_BIN=`./tool/get_chrome_canary.sh`
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - nvm install 5.5.0
  - npm install
script:
  #- ./tool/presubmit.sh && ./tool/coverage.sh
  - ./tool/$TEST_TO_RUN.sh
env:
  - TEST_TO_RUN=check_expectations_were_built
  - TEST_TO_RUN=coverage
  - TEST_TO_RUN=test
  - TEST_TO_RUN=browser_test
  - TEST_TO_RUN=node_test
  - TEST_TO_RUN=analyze
  - TEST_TO_RUN=format
  - TEST_TO_RUN=transformer_test
  #- TEST_TO_RUN=transformer_e2e_test
