language: dart
sudo: false
dart:
  - dev
before_install:
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 
  - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable google-chrome-beta google-chrome-unstable
  - google-chrome --version
  - google-chrome-unstable --version
  - google-chrome-beta --version
  - chromium-browser --version
  - pub global activate dart_coveralls
  - export CHROME_URL=https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64
  - export CHROME_REV=$(curl -s ${CHROME_URL}/LAST_CHANGE)
  - curl ${CHROME_URL}/${CHROME_REV}/chrome-linux.zip --create-dirs -o out/chrome-linux.zip
  - unzip out/chrome-linux.zip -d out
  - export CHROME_CANARY_BIN=$PWD/out/chrome-linux/chrome
  - export CHROME_BIN=google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm install
script:
  - ./tool/presubmit.sh
  - ./tool/coverage.sh
