name: dev_compiler
description: Dart dev checker / compiler
dependencies:
  analyzer:
    git:
      url: https://github.com/dart-lang/ddc_analyzer.git
      ref: master
  args: ^0.12.1
  cli_util: ^0.0.1
  crypto: ^0.9.0
  # We pin a specific version to ensure everyone is formatting the code exactly
  # the same way. This is because any change in dart_style, even non-braking
  # changes, may change the output format.
  dart_style: 0.1.7
  html5lib: ^0.12.0
  logging: ^0.9.2
  path: ^1.3.0
  shelf: ^0.6.0
  shelf_static: ^0.2.1
  source_maps: ^0.10.0
  source_span: ^1.0.0
  stack_trace: ^1.1.1
  yaml: ^2.1.2
dev_dependencies:
  pub_semver: ^1.1.0
  unittest: ^0.11.0
dependency_overrides:
  analyzer:
    git:
      url: https://github.com/dart-lang/ddc_analyzer.git
      ref: master
executables:
  # Similar to "analyzer.dart" and its command line "dartanalyzer", we use
  # "dartdevc" and "devc.dart"
  dartdevc: devc
