name: ddc
description: Dart dev checker / compiler
dependencies:
  analyzer: ">=0.22.4 <0.23.0"
  args: ">=0.12.1 <0.13.0"
  logging: ">=0.9.2 <0.10.0"
  source_span: ">=1.0.0 <2.0.0"
  path: ">=1.3.0 <2.0.0"
dev_dependencies:
  unittest: ">=0.11.0 <0.12.0"
