name: ddc
description: Dart dev checker / compiler
dependencies:
  analyzer:
    git:
      url: http://github.com/dart-lang/analyzer-for-ddc.git
      ref: master
  args: ^0.12.1
  cli_util: ^0.0.1
  dart_style:
    git:
      url: http://github.com/dart-lang/dart_style.git
      # TODO(jmesserly): pinned until we can upgrade analyzer-for-ddc
      ref: 5a3a2287d72a635c3041ba54404db25b5cd75f5e
  logging: ^0.9.2
  source_span: ^1.0.0
  path: ^1.3.0
  source_maps: ^0.10.0
  stack_trace: ^1.1.1
dev_dependencies:
  unittest: ^0.11.0
  pub_semver: ^1.1.0
dependency_overrides:
  analyzer:
    git:
      url: git@github.com:dart-lang/analyzer-for-ddc.git
      ref: master
executables:
  # Similar to "analyzer.dart" and its command line "dartanalyzer", we use
  # "dartdevc" and "devc.dart"
  dartdevc: devc
