name: dev_compiler
version: 0.1.0
description: >
  Experimental Dart to JavaScript compiler designed to create idiomatic,
  readable JavaScript output.
author: Dart Dev Compiler team <dev-compiler@dartlang.org>
homepage: https://github.com/dart-lang/dev_compiler
dependencies:
  analyzer: ^0.25.0
  args: ^0.13.0
  cli_util: ^0.0.1
  crypto: ^0.9.0
  html: ^0.12.0
  logging: ">=0.9.3 <0.12.0"
  path: ^1.3.0
  shelf: ^0.6.0
  shelf_static: ^0.2.1
  source_maps: ^0.10.0
  source_span: ^1.1.2
  stack_trace: ^1.1.1
  yaml: ^2.1.2
dev_dependencies:
  # We pin a specific version to ensure everyone is formatting the code exactly
  # the same way. This is because any change in dart_style, even non-breaking
  # changes, may change the output format.
  dart_style: 0.1.8
  pub_semver: ^1.1.0
  test: ^0.12.0
environment:
  sdk: ">=1.9.0 <2.0.0"
executables:
  # Similar to "analyzer.dart" and its command line "dartanalyzer", we use
  # "dartdevc" and "devc.dart"
  dartdevc: devc
