name: ddc
description: Dart dev checker / compiler
dependencies:
  analyzer:
    git:
      url: http://github.com/dart-lang/analyzer-for-ddc.git
      ref: master
  args: ">=0.12.1 <0.13.0"
  dart_style:
    git:
      url: http://github.com/dart-lang/dart_style.git
      ref: master
  logging: ">=0.9.2 <0.10.0"
  source_span: ">=1.0.0 <2.0.0"
  path: ">=1.3.0 <2.0.0"
  source_maps: ">=0.10.0 <0.11.0"
dev_dependencies:
  unittest: ">=0.11.0 <0.12.0"
dependency_overrides:
  analyzer:
    git:
      url: http://github.com/dart-lang/analyzer-for-ddc.git
      ref: master
executables:
  # Similar to "analyzer.dart" and its command line "dartanalyzer", we use
  # "dartdevc" and "devc.dart"
  dartdevc: devc
