name: ddc_example_transformer_app
version: 0.0.1
dependencies:
  ddc_example_transformer_dep:
    path: ../hello_dep
dev_dependencies:
  barback: any
  dev_compiler:
    path: ../../..
transformers:
- dev_compiler:
    args:
      - --closure
      - --destructure-named-params
- $dart2js:
    $exclude: '**'
